version: "3.8"
services:
  mongo:
    image: geppettotest/mongo-local:april2020
    container_name: mongo-9432
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - cds_9432-volume:/data/db
    ports:
      - "27018:27017"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u root -p root --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  camunda:
    image: geppettodistribution/camunda-local:Jan2021
    container_name: camunda-9432
    ports:
      - "0000:8080"

  authproxy:
    build: ../../../application/services/default_services/authproxy
    image: authproxy-9432
    container_name: authproxy-9432
    ports:
      - "0000:8001"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  securitymanager:
    build: ../../../application/services/default_services/securitymanager
    image: securitymanager-9432
    container_name: securitymanager-9432
    ports:
      - "8003:8003"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  camundaservice:
    build: ../../../application/services/default_services/camunda
    image: camundaservice-9432
    container_name: camundasvc-9432
    ports:
      - "8002:8002"
    env_file: .env
    depends_on:
      - mongo
      - camunda
      - securitymanager

  apigateway:
    build: ../../../application/services/custom_services/apigateway
    image: apigateway-9432
    container_name: apigateway-9432
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - camunda
      - camundaservice
      - authproxy
      - securitymanager
      - student



  student: 
    build: ../../../application/services/custom_services/student
    image: student-9432
    container_name: student-9432
    ports: 
      - 8005:8005
    env_file: .env
    depends_on:
      - mongo


volumes:
  cds_9432-volume:
    driver: local
